### ISSUE TITLE
Integrate Professors into Course Page to fetch data from Firebase

### ISSUE THREAD

**Issue by th3pi** [th3pi/CS370-Team-TBA#23]
Integrate Professors model and utils to dynamically fetch professor details based on course name.

### Tasks

- [x] Professor name dynamically fetched from Firebase
- [x] Professor email dynamically fetched from Firebase
- [x] Professor website dynamically fetched from Firebase
